### PR TITLE
add conversion from unicode to int

### PR DESCRIPTION
**Pull request by mkudlej**

### CODE REVIEW

**Comment by mkudlej** [comment]
@r0h4n Please review

**Comment by mkudlej** [comment]
@anmolbabu Please review

**Comment by mkudlej** [comment]
@anmolbabu any update?

**Comment by r0h4n** [comment]
Looks good, please send this PR to develop branch

**Comment by anmolbabu** [comment]
@mkudlej @r0h4n I have fixed this as part of namespacing changes patch

**Comment by mbukatov** [comment]
@mkudlej Could you provide a proper description for the pull request? I have no idea what is this about. Moreover I don't understand why is this closed while unmerged? Is this no longer needed based on latest changes?

**Comment by mkudlej** [comment]
I will delete this branch.

**Pull request closed without merging**
