### PR TITLE
Replace cluster id with integration_id

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: Tendrl/performance-monitoring#199
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Needs to be verified...
This PR needs makes changes on UI and API necessary..
It changes all occurrences of cluster_id or cluster-id to integration_id
cc: @anivargi @cloudbehl @gnehapk

**Comment by anmolbabu** [comment]
The following PRs:

- https://github.com/Tendrl/alerting/pull/96

- https://github.com/Tendrl/node-monitoring/pull/73

- https://github.com/Tendrl/performance-monitoring/pull/216

are all interrelated and need to go in together...

**Comment by anmolbabu** [comment]
Needs to be verified...

**Comment by r0h4n** [comment]
Please send this PR on "master" branch

**Pull request merged**
