### PR TITLE
Fix service stop issue

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
All processes in the control group of this unit
will be killed on unit stop

tendrl-bug-id: Tendrl/performance-monitoring/#42
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@ktdreyer, @r0h4n , @nthomas-redhat , @shtripat , @anmolbabu , Please review

**Comment by ktdreyer** [comment]
`control-group` is already the [systemd default](https://www.freedesktop.org/software/systemd/man/systemd.kill.html). I recommend simply removing `KillMode` from your service unit file altogether.

**Comment by TimothyAsir** [comment]
Sure, i will do it, Thank you

**Comment by ktdreyer** [comment]
Two commits that do slightly different things, but the Git commit logs are the same?

**Comment by ktdreyer** [comment]
Want to squash those down to one commit so it's clearer?

**Pull request merged**
