### PR TITLE
Add support for interval and time based queries for stats

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: https://github.com/Tendrl/dashboard/issues/322
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
@r0h4n @shtripat @nthomas-redhat Please review

**Comment by anmolbabu** [comment]
Verified

**Comment by anmolbabu** [comment]
This pr adds optional parameters:
1. start_time: Any date-time that is intended to be used as start datetime of a date range for which stats are required
2. end_time: Any date-time that is intended to be used as end datetime of a date range for which stats are required
3. interval: Interval for which the stats are required..

The first 2 are currently not going to be of any use while 3rd one will be used by UI to workaround issue: https://github.com/Tendrl/dashboard/issues/322... And hence much importance is not given to the first 2 options(i.e, currently time zone related handling is not in place... will be added in a follow-up PR though)...
Now the interval can be specified as :
- -12h -- To indicate last 12 hrs
- -6min -- To indicate last 6 mins
- -5s -- To indicate last 5 seconds
Certain stats are queried once every 10 mins some 1 min and a few others once every 5 mins
So in my opinion its better for us to choose anything in excess of 15 mins as a safe interval for query(unless we decide to go with per stat custom interval of query from UI)

**Comment by r0h4n** [comment]
The only datetime you should be handling is in UTC. Let the UI convert it to user's timezone.

**Pull request merged**
