### PR TITLE
monitoring: Api fixes

### PR DESCRIPTION
**Pull request by anmolbabu**
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Needs to verified...

**Comment by anmolbabu** [comment]
Please don't merge this is..

**Comment by r0h4n** [comment]
Ack

**Comment by anmolbabu** [comment]
Verified..

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat @shtripat please review

**Pull request merged**
